### ISSUE TITLE
Supplementary figures

### ISSUE THREAD

**Issue by KulaginVladimir** [KulaginVladimir/FESTIM-SurfaceKinetics-Validation#18]
From discussions, some validation cases need additional figures. 

- [x] Schematic diagram of surface processes #12 
- [x] The temperature evolution in "D in Eurofer" case #24 
- [x] Evolution of the surface concentration in "D damagedW" case #20

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin 

Now I don't think that we require a figure for "The dependence of desorption energy on the surface coverage in the "D in WO" case?". Therefore, I'd close this issue as completed

**Comment by RemDelaporteMathurin** [comment]
SGTM
